council/urls.py
""" Django URL routing """
from django.urls import path
from . import views

app_name = 'council'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.AgencyView.as_view(), name='agency-detail'),
    path('department/<int:pk>/', views.DepartmentView.as_view(), name='department-detail'),
    path('agenda/<int:pk>/', views.AgendaView.as_view(), name='agenda-detail'),
    path('department/<int:pk>/fetch', views.DepartmentFetchView.as_view(), name='fetch-agendas'),
    path('agenda/<int:pk>/convert', views.AgendaConvertView.as_view(), name='convert-pdf'),
    path('agenda/<int:pk>/highlight', views.AgendaHighlightView.as_view(), name='highlight'),
]

mypractice/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls')),
    path('council/', include('council.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),
]

council/crawlers/controller.py
"""
This is a controller linking Crawler objects and their
corresponding crawler modules. The controller creates
new Agenda objects and adds them to the database.
"""
from datetime import datetime
from django.utils.timezone import get_current_timezone
from ..crawlers import edmond
from ..crawlers import el_reno
from ..crawlers import lawton
from ..crawlers import midwest_city
from ..crawlers import moore
from ..crawlers import norman
from ..crawlers import okc
from ..crawlers import tulsa
from ..models import Agenda, Highlight, Keyphrase
from ..modules import word_search as wsearch

def exec_crawler(crawler, calling_department):
    """ Linking function between Crawler models and Crawler modules. """

    if crawler.crawler_name == "Edmond":
        edmond_crawler(calling_department)

    elif crawler.crawler_name == "El Reno":
        el_reno_crawler(calling_department)

    elif crawler.crawler_name == "Lawton":
        lawton_crawler(calling_department)

    elif crawler.crawler_name == "Midwest City":
        midwest_city_crawler(calling_department)

    elif crawler.crawler_name == "Moore":
        moore_crawler(calling_department)

    elif crawler.crawler_name == "Oklahoma City":
        okc_crawler(calling_department)

    elif crawler.crawler_name == "Norman":
        norman_crawler(calling_department)

    elif crawler.crawler_name == "Tulsa":
        tulsa_crawler(calling_department)

def agenda_exists(agenda_url):
    """
    This function takes an agenda URL and makes sure that it is not
    already associated with an agenda in the database.
    """
    return bool(Agenda.objects.filter(agenda_url=agenda_url).exists())

def hl_exists(agenda, hl_start, hl_end):
    """
    This function takes an agenda and a highlight range and checks that
    it is not already in the database.
    """
    agenda_highlights = Highlight.objects.filter(agenda=agenda)
    for highlight in agenda_highlights:
        return bool(highlight.hl_start == hl_start and \
            highlight.hl_end == hl_end)

def gen_highlights(agenda):
    """
    This function takes an agenda and searches it for keyphrase
    matches. If any are found, they are saved as highlights.
    """
    keyphrases = Keyphrase.objects.all()
    for keyphrase in keyphrases:
        matches = wsearch.match_lines(agenda.agenda_text, keyphrase.kp_text)
        for match in matches:
            if not hl_exists(agenda, match.get("start"), match.get("end")):
                new_hl = Highlight(
                    hl_start=match.get("start"),
                    hl_end=match.get("end"),
                    date_added=datetime.now(tz=get_current_timezone()),
                    agenda=agenda,
                    category=keyphrase.category
                )
                new_hl.save()

def edmond_crawler(calling_department):
    """ Edmond Crawler function. """
    agendas_url = calling_department.agendas_url
    agenda_name = calling_department.department_name
    agenda_html = edmond.retrieve_current_agendas(agendas_url)
    specific_agendas = edmond.find_specific_agendas(agenda_html, agenda_name)
    for agenda in specific_agendas:
        agenda_url = agenda.get("agenda_url")
        if not agenda_exists(agenda_url):
            parsed_agenda = edmond.get_agenda(agenda_url)
            parsed_agenda.update(
                {
                    "agenda_date": agenda.get("agenda_date"),
                    "agenda_name": agenda_name
                }
            )
            new_agenda = Agenda(
                agenda_date=parsed_agenda.get("agenda_date"),
                agenda_title=parsed_agenda.get("agenda_name"),
                agenda_url=parsed_agenda.get("agenda_url"),
                agenda_text=parsed_agenda.get("agenda_text"),
                pdf_link=parsed_agenda.get("pdf_link"),
                date_added=datetime.now(tz=get_current_timezone()),
                department=calling_department
            )
            new_agenda.save()

def el_reno_crawler(calling_department):
    """ El Reno Crawler function. """
    agendas_url = calling_department.agendas_url
    agendas_list = el_reno.retrieve_agendas(agendas_url)
    recent_agendas = el_reno.get_most_recent_agendas(agendas_list)
    for agenda in recent_agendas:
        agenda_url = agenda.a["href"]
        if not agenda_exists(agenda_url):
            parsed_agenda = el_reno.parse_agenda_info(agenda)
            new_agenda = Agenda(
                agenda_date=parsed_agenda.get("agenda_date"),
                agenda_title=parsed_agenda.get("agenda_title"),
                agenda_url=parsed_agenda.get("agenda_url"),
                agenda_text=parsed_agenda.get("agenda_text"),
                pdf_link=parsed_agenda.get("pdf_link"),
                date_added=datetime.now(tz=get_current_timezone()),
                department=calling_department
            )
            new_agenda.save()

def lawton_crawler(calling_department):
    """ Lawton Crawler function. """
    agendas_url = calling_department.agendas_url
    agendas_list = lawton.retrieve_agendas(agendas_url)
    print("Attempting to find any matching agendas")
    matched_agendas = lawton.match_agendas(agendas_list, calling_department.department_name)
    for agenda in matched_agendas:
        print("Agenda match found. Attemping to get agenda URL...")
        agenda_url = lawton.get_agenda_url(agenda.get("agenda_detail_url"))
        print("URL found. Checking to see if it already exists in db...")
        if not agenda_exists(agenda_url):
            agenda_text = lawton.get_agenda_text(agenda_url)
            print("Agenda does not yet exist. Preparing to add to db...")
            new_agenda = Agenda(
                agenda_date=agenda.get("agenda_date"),
                agenda_title=agenda.get("agenda_title"),
                agenda_url=agenda_url,
                agenda_text=agenda_text,
                pdf_link=agenda_url,
                date_added=datetime.now(tz=get_current_timezone()),
                department=calling_department
            )
            new_agenda.save()
        else:
            print("Agenda already exists in db. Aborting.")

def midwest_city_crawler(calling_department):
    """ Midwest City Crawler function. """
    agendas_url = calling_department.agendas_url
    agendas_list = midwest_city.retrieve_agendas(agendas_url)
    print("Attempting to find any matching agendas")
    matched_agendas = midwest_city.match_agendas(agendas_list, calling_department.department_name)
    for agenda in matched_agendas:
        print("Agenda match found. Checking URL against database...")
        agenda_url = agenda.get("agenda_url")
        if not agenda_exists(agenda_url):
            print("Agenda does not yet exist. Converting PDF to text...")
            agenda_text = midwest_city.get_agenda_text(agenda_url)
            print("Conversion complete. Preparing to add to db...")
            new_agenda = Agenda(
                agenda_date=agenda.get("agenda_date"),
                agenda_title=agenda.get("agenda_title"),
                agenda_url=agenda_url,
                agenda_text=agenda_text,
                pdf_link=agenda_url,
                date_added=datetime.now(tz=get_current_timezone()),
                department=calling_department
            )
            new_agenda.save()
        else:
            print("Agenda already exists in db. Aborting.")

def moore_crawler(calling_department):
    """ Moore Crawler function. """
    agendas_url = calling_department.agendas_url
    agendas_list = moore.retrieve_agendas(agendas_url)
    print("Attempting to find any matching agendas")
    matched_agendas = moore.match_agendas(agendas_list, calling_department.department_name)
    for agenda in matched_agendas:
        print("Agenda match found. Attemping to get agenda URL...")
        agenda_url = moore.get_agenda_url(agenda.get("agenda_detail"))
        if agenda_url:
            print("Agenda found. Check to see if it already exists in db...")
            if not agenda_exists(agenda_url):
                agenda_text = moore.get_agenda_text(agenda_url)
                print("Agenda does not yet exist. Preparing to add to db...")
                new_agenda = Agenda(
                    agenda_date=agenda.get("agenda_date"),
                    agenda_title=agenda.get("agenda_title"),
                    agenda_url=agenda_url,
                    agenda_text=agenda_text,
                    pdf_link=agenda_url,
                    date_added=datetime.now(tz=get_current_timezone()),
                    department=calling_department
                )
                new_agenda.save()
            else:
                print("Agenda already exists in db. Aborting.")
        else:
            print("No agenda has been posted yet. Try again later.")

def norman_crawler(calling_department):
    """ Norman Crawler function. """
    agendas_url = calling_department.agendas_url
    agendas_list = norman.retrieve_agendas(agendas_url)
    print("Attempting to find any matching agendas")
    matched_agendas = norman.match_agendas(agendas_list, calling_department.department_name)
    for agenda in matched_agendas:
        print("Agenda found. Check to see if it already exists in db...")
        agenda_url = agenda.get("agenda_url")
        if not agenda_exists(agenda_url):
            print("Agenda does not yet exist. Converting PDF to text...")
            agenda_text = norman.get_agenda_text(agenda_url)
            print("Agenda does not yet exist. Preparing to add to db...")
            new_agenda = Agenda(
                agenda_date=agenda.get("agenda_date"),
                agenda_title=agenda.get("agenda_title"),
                agenda_url=agenda_url,
                agenda_text=agenda_text,
                pdf_link=agenda_url,
                date_added=datetime.now(tz=get_current_timezone()),
                department=calling_department
            )
            new_agenda.save()
        else:

council/views.py
""" Views for the application """
from datetime import date, timedelta
from django.views import generic
from council.models import Agency, Department, Agenda
from council.tasks import convert_pdf_to_text, fetch_agendas, generate_highlights

# Create your views here.

class IndexView(generic.ListView):
    """ View for the index page of the application """
    template_name = 'council/index.html'

    def get_queryset(self):
        return Agency.objects.order_by('agency_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_date = date.today()
        start = current_date - timedelta(days=current_date.weekday())
        end = start + timedelta(days=4)
        this_weeks_agendas = Agenda.objects.filter(
            agenda_date__range=(start, end)).order_by('agenda_date')
        context['this_weeks_agendas'] = this_weeks_agendas
        return context

class AgencyView(generic.DetailView):
    """ View for the agency detail page """
    model = Agency
    template_name = 'council/agency_detail.html'

class DepartmentView(generic.DetailView):
    """ View for the department detail page """
    model = Department
    template_name = 'council/department_detail.html'

class DepartmentFetchView(generic.DetailView):
    """ View for the department fetch agendas page """
    model = Department
    template_name = 'council/department_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result = fetch_agendas.delay(context['department'].pk)
        context['task_id'] = result.task_id
        return context

class AgendaView(generic.DetailView):
    """ View for the agenda detail page """
    model = Agenda
    template_name = 'council/agenda_detail.html'

    def get(self, request, *args, **kwargs):
        """ On page get, set viewed attribute to true """
        agenda = Agenda.objects.get(pk=self.get_object().id)
        agenda.viewed = True
        agenda.save()
        return super(AgendaView, self).get(request, *args, **kwargs)

class AgendaConvertView(generic.DetailView):
    """ View for the agenda convert  page """
    model = Agenda
    template_name = 'council/agenda_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result = convert_pdf_to_text.delay(context['agenda'].pk)
        context['convert_task_id'] = result.task_id
        return context

class AgendaHighlightView(generic.DetailView):
    """ View for the agenda generate highlights page """
    model = Agenda
    template_name = 'council/agenda_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result = generate_highlights.delay(context['agenda'].pk)
        context['highlight_task_id'] = result.task_id
        return context

council/templates/council/agency_detail.html
<!-- templates/agency-detail.html -->
{% extends 'base.html' %}

{% block title %} | Council Insights | {{ agency.agency_name }}{% endblock %}

{% block content %}
{% load breadcrumbs %}
{% block breadcrumbs %}
    {% breadcrumb "My Practice" "home" %}
    {% breadcrumb "Council Insights" "council:index" %}
    {% breadcrumb agency "council:agency-detail" agency.id %}
{% endblock %}
{% render_breadcrumbs %}

<!-- Agency name for page heading -->
<h2>{{ agency.agency_name }}</h2>

<hr></hr>

<!-- List departments -->
<div class="card border-light mb-3">
    <h5 class="card-header">Departments</h5>
    <div class="card-body">
    {% if agency.departments.all.exists %}
        <div class="list-group">
            {% for department in agency.departments.all %}
            <a class="list-group-item list-group-item-action" href="{% url 'council:department-detail' department.id %}">{{ department.department_name }}</a>
            {% endfor %}
        </div>
    {% else %}
        <p>No departments have been added to this agency yet.</p>
    {% endif %}
    </div>

{% endblock %}

council/templates/council/agenda_detail.html
<!-- templates/agenda-detail.html -->
{% extends 'base.html' %}

{% load customtags %}

{% block title %} | Council Insights | {{ agenda.department.agency.agency_name }} | {{ agenda.department.department_name }} | {{ agenda.agenda_date|date:"m/d/y" }} Agenda Detail{% endblock %}

{% block content %}
{% load breadcrumbs %}
{% block breadcrumbs %}
    {% breadcrumb "My Practice" "home" %}
    {% breadcrumb "Council Insights" "council:index" %}
    {% breadcrumb agenda.department.agency "council:agency-detail" agenda.department.agency.id %}
    {% breadcrumb agenda.department "council:department-detail" agenda.department.id %}
    {% breadcrumb agenda "council:agenda-detail" agenda.id %}
{% endblock %}
{% render_breadcrumbs %}

<!-- Agenda date and title for page heading -->
<h2>{{ agenda.agenda_date|date:"m/d/y" }} {{ agenda.agenda_title }}</h2>

<hr></hr>

<!-- Highlights -->
<div id="highlights" class="card border-light mb-3">
    <h5 class="card-header">Highlights
        <small class="mt-1 text-muted" style="float: right;"><a href="{% url 'council:highlight' agenda.id %}">Generate Highlights</a></small>
    </h5>
    <div class="card-body">
    {% if highlight_task_id %}
        {% load static %}
        <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
        <div class='progress' style="height: 20px;">
            <div id='highlight-progress-bar' class='progress-bar progress-bar-striped progress-bar-animated' style="width: 0%;">&nbsp;</div>
        </div>
        <div id="highlight-progress-message">Preparing to generate highlights...</div>
        <div id="highlight-celery-result"></div>
        <script>
            function sleep(ms) {
                return new Promise(resolve => setTimeout(resolve, ms));
            }
            function customProgress(progressBarElement, progressBarMessageElement, progress) {
                progressBarElement.style.backgroundColor = '#68a9ef';
                if (progress.description != undefined) {
                    progressBarElement.style.width = progress.percent + "%";
                    var description = progress.description;
                    progressBarMessageElement.innerHTML = description;
                }
            }
            function customSuccess(progressBarElement, progressBarMessageElement) {
                progressBarElement.style.backgroundColor = '#76ce60';
                progressBarElement.style.width = "100%";
                progressBarMessageElement.innerHTML = "Complete. Refreshing highlight display...";
                
            }
            function customError(progressBarElement, progressBarMessageElement) {
                progressBarElement.style.backgroundColor = '#dc4f63';
                progressBarMessageElement.innerHTML = "A problem was encountered while trying to generate highlights.";
            }
            async function customResult(resultElement, result) {
                await sleep(3000);
                window.location.replace("{% url 'council:agenda-detail' agenda.id %}");
            }
            document.addEventListener("DOMContentLoaded", function () {
                var progressUrl = "{% url 'celery_progress:task_status' highlight_task_id %}";
                CeleryProgressBar.initProgressBar(
                    progressUrl,
                    {
                        progressBarId: 'highlight-progress-bar',
                        progressBarMessageId: 'highlight-progress-message',
                        resultElementId: 'highlight-celery-result',
                        onProgress: customProgress,
                        onSuccess: customSuccess,
                        onError: customError,
                        onResult: customResult
                    });
            });
        </script>
    {% else %}
        {% if agenda.highlights.all %}
            <ul>
            {% for highlight in agenda.highlights.all|order_by:"start" %}
                <li><a href="#{{ highlight.id }}">{{ agenda.agenda_text|hl_slice:highlight|truncatechars:500 }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            There are no highlights for this document based on current keyphrases, or highlights have not yet been generated.
        {% endif %}
    {% endif %}
    </div>
</div>

<!-- Agenda Content -->
<div id="agendas" class="card border-light mb-3">
    <h5 class="card-header">Agenda Content
    {% if agenda.pdf_link %}
        <small class="mt-1 text-muted" style="float: right;"><a href="{{ agenda.pdf_link }}" target="_blank">Download PDF</a></small>
    {% endif %}
    </h5>
    <div class="card-body">
    {% if agenda.agenda_text %}
        {% if agenda.highlights.all %}
        <script>
            $(document).ready(function(){
                // Displays highlights if any exist
                {% for highlight in agenda.highlights.all %}
                $( "div.card-body div.mb-3:contains('{{ agenda.agenda_text|hl_slice:highlight|safe }}')" ).css( "background-color", "#FFFF00" ).attr("id", "{{ highlight.id }}");
                {% endfor %}
            });
        </script>
        {% endif %}
        {{ agenda.agenda_text|safe|linebreaks }}
    {% else %}
        {% if convert_task_id %}
            {% load static %}
            <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
            <div class='progress' style="height: 20px;">
                <div id='convert-progress-bar' class='progress-bar progress-bar-striped progress-bar-animated' style="width: 0%;">&nbsp;</div>
            </div>
            <div id="convert-progress-message">Attempting to connect...</div>
            <div id="convert-celery-result"></div>
            <script>
                function sleep(ms) {
                    return new Promise(resolve => setTimeout(resolve, ms));
                }
                function customProgress(progressBarElement, progressBarMessageElement, progress) {
                    progressBarElement.style.backgroundColor = '#68a9ef';
                    if (progress.description != undefined) {
                        progressBarElement.style.width = progress.percent + "%";
                        var description = progress.description;
                        progressBarMessageElement.innerHTML = description;
                    }
                }
                function customSuccess(progressBarElement, progressBarMessageElement) {
                    progressBarElement.style.backgroundColor = '#76ce60';
                    progressBarElement.style.width = "100%";
                    progressBarMessageElement.innerHTML = "Complete. Refreshing agenda content...";
                    
                }
                function customError(progressBarElement, progressBarMessageElement) {
                    progressBarElement.style.backgroundColor = '#dc4f63';
                    progressBarMessageElement.innerHTML = "Unable to convert PDF. An exception was raised during the conversion process.";
                }
                async function customResult(resultElement, result) {
                    await sleep(3000);
                    window.location.replace("{% url 'council:agenda-detail' agenda.id %}");
                }
                document.addEventListener("DOMContentLoaded", function () {
                    var progressUrl = "{% url 'celery_progress:task_status' convert_task_id %}";
                    CeleryProgressBar.initProgressBar(
                        progressUrl,
                        {
                            progressBarId: 'convert-progress-bar',
                            progressBarMessageId: 'convert-progress-message',
                            resultElementId: 'convert-celery-result',
                            onProgress: customProgress,
                            onSuccess: customSuccess,
                            onError: customError,
                            onResult: customResult
                        });
                });
            </script>
        {% else %}
            <p>Agenda text has not yet been generated. Click <a href="{% url 'council:convert-pdf' agenda.id %}">here</a>
                to convert the agenda PDF into text. Note: this may take a few minutes</p>
        {% endif %}
    {% endif %}
    </div>
</div>

{% endblock %}

council/templates/council/department_detail.html
<!-- templates/department-detail.html -->
{% extends 'base.html' %}

{% block title %} | Council Insights | {{ department.agency.agency_name }} 
    | {{ department.department_name }}{% endblock %}

{% block content %}
{% load breadcrumbs %}
{% block breadcrumbs %}
    {% breadcrumb "My Practice" "home" %}
    {% breadcrumb "Council Insights" "council:index" %}
    {% breadcrumb department.agency "council:agency-detail" department.agency.id %}
    {% breadcrumb department "council:department-detail" department.id %}
{% endblock %}
{% render_breadcrumbs %}

<!-- Department and agency name for page heading -->
<h2>{{ department.department_name }} <small class="text-muted">{{ department.agency.agency_name }}</small></h2>

<hr></hr>

{% if department.meeting_info %}
<!-- Meeting information -->
<div class="card border-light mb-3">
    <h5 class="card-header">Meeting Information</h5>
    <div class="card-body">{{ department.meeting_info }}</div>
</div>
{% endif %}

<!-- List agendas -->
<div class="card border-light mb-3">
<h5 class="card-header">Agendas
{% if department.agendas_url %}
    <small class="mt-1 text-muted" style="float: right;"><a href="{{ department.agendas_url }}" target="_blank">City Website</a> | 
        <a href="{% url 'council:fetch-agendas' department.id %}">Fetch New Agendas</a>
    </small>
{% endif %}
</h5>
        
    <div class="card-body">
        {% if task_id %}
        <!-- Progress bar -->
        {% load static %}
        <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
        <div class='progress' style="height: 20px;">
            <div id='progress-bar' class='progress-bar progress-bar-striped progress-bar-animated' style="width: 0%;">&nbsp;</div>
        </div>
        <div id="progress-bar-message">Connecting to City website...</div>
        <div class="mb-3" id="celery-result"></div>
        <script>
            function sleep(ms) {
                return new Promise(resolve => setTimeout(resolve, ms));
            }
            function customProgress(progressBarElement, progressBarMessageElement, progress) {
                progressBarElement.style.backgroundColor = '#68a9ef';
                if (progress.description != undefined) {
                    progressBarElement.style.width = progress.percent + "%";
                    var description = progress.description;
                    progressBarMessageElement.innerHTML = description;
                }
            }
            function customSuccess(progressBarElement, progressBarMessageElement) {
                progressBarElement.style.backgroundColor = '#76ce60';
                progressBarElement.style.width = "100%";
                progressBarMessageElement.innerHTML = "Fetching complete. Reloading agenda list...";
            }
            function customError(progressBarElement, progressBarMessageElement, data) {
                progressBarElement.style.backgroundColor = '#dc4f63';
                progressBarMessageElement.innerHTML = "Unable to fetch agendas. An exception was raised during the process.";
            }
            async function customResult(resultElement, result) {
                await sleep(3000);
                window.location.replace("{% url 'council:department-detail' department.id %}");
            }
            document.addEventListener("DOMContentLoaded", function () {
                var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
                CeleryProgressBar.initProgressBar(
                    progressUrl,
                    {
                        onProgress: customProgress,
                        onSuccess: customSuccess,
                        onError: customError,
                        onResult: customResult
                    });
            });
        </script>
            {% if department.agendas.all.exists %}
            <div class="list-group">
                {% for agenda in department.agendas.all %}
                    {% if agenda.active %}
                    <a class="list-group-item list-group-item-action" href="{% url 'council:agenda-detail' agenda.id %}">
                        {{ agenda.agenda_date|date:"m/d/y" }} {{ agenda.agenda_title }} {% if agenda.is_new %}<span class="badge badge-danger">New</span>{% endif %}</a>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
        {% else %}
            {% if department.agendas.all.exists %}
            <div class="list-group">
                {% for agenda in department.agendas.all %}
                    {% if agenda.active %}
                    <a class="list-group-item list-group-item-action" href="{% url 'council:agenda-detail' agenda.id %}">
                        {{ agenda.agenda_date|date:"m/d/y" }} {{ agenda.agenda_title }} {% if agenda.is_new %}<span class="badge badge-danger">New</span>{% endif %}</a>
                    {% endif %}
                {% endfor %}
                </div>
            {% else %}No agendas have been added for this department yet.
            {% endif %}
        {% endif %}
    </div>
</div>

{% endblock %}

council/templates/council/index.html
<!-- templates/index.html -->
{% extends 'base.html' %}

{% block title %} | Council Insights | Home{% endblock %}

{% block content %}
{% load breadcrumbs %}
{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "My Practice" "home" %}
    {% breadcrumb "Council Insights" "council:index" %}
{% endblock %}
{% render_breadcrumbs %}

<h2>Council Insights</h2>

<hr></hr>

<div class="card border-light mb-3">
    <h5 class="card-header">Meetings This Week</h5>
    <div class="card-body">
        {% if this_weeks_agendas %}
        <ul>
            {% for agenda in this_weeks_agendas %}
            <li><a href="{% url 'council:agenda-detail' agenda.id %}">{{ agenda.agenda_date }} - {{ agenda.department.agency }} - {{ agenda.department }}</a></li>
            {% endfor %}
        </ul>
        {% else %}No tracked meetings this week.
        {% endif %}
    </div>
</div>

<div class="card border-light mb-3">
    <h5 class="card-header">Agencies</h5>
    <div class="card-body">
    {% if agency_list %}
        <div class="list-group">
            {% for agency in agency_list %}
            <a class="list-group-item list-group-item-action" href="{% url 'council:agency-detail' agency.id %}">{{ agency.agency_name }}</a>
            {% endfor %}
        </div>
    {% else %}No agencies have been added to track yet.
    {% endif %}
    </div>
{% endblock %}