council/urls.py
""" Django URL routing """
from django.urls import path
from . import views

app_name = 'council'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.AgencyView.as_view(), name='agency-detail'),
    path('department/<int:pk>/', views.DepartmentView.as_view(), name='department-detail'),
    path('agenda/<int:pk>/', views.AgendaView.as_view(), name='agenda-detail'),
    path('department/<int:pk>/fetch', views.DepartmentFetchView.as_view(), name='fetch-agendas'),
    path('agenda/<int:pk>/convert', views.AgendaConvertView.as_view(), name='convert-pdf'),
    path('agenda/<int:pk>/highlight', views.AgendaHighlightView.as_view(), name='highlight'),
]

mypractice/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls')),
    path('council/', include('council.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),
]

projects/urls.py
""" URLs for Projects app """
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <title>My Practice{% block title %}{% endblock %}</title>
</head>
<body>
  <main>
    <div class="container mt-3">
      {% block content %}
      {% endblock %}
    </div>
  </main>
</body>
<footer>
  {% if user.is_authenticated %}
    <div class="container text-muted">
      <hr></hr>
      <p><a href="{% url 'logout' %}">Logout</a> | 
      <a href="{% url 'admin:index' %}">Admin</a></p>
    </div>
  {% endif %}
</footer>
</html>

templates/breadcrumbs.html
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% for url, label in breadcrumbs %}
        {% if not url or forloop.counter == breadcrumbs_total %}
          <li class="breadcrumb-item{% if forloop.counter == breadcrumbs_total %} active{% endif %}" {% if forloop.counter == breadcrumbs_total %}aria-current="page"{% endif %}>{{ label|safe }}</li>
        {% else %}
          <li class="breadcrumb-item"><a href="{{ url }}">{{ label|safe }}</a></li>
        {% endif %}
      {% endfor %}
    </ol>
</nav>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

<h2>My Practice</h2>

<hr></hr>

{% if user.is_authenticated %}
<div class="card border-light mb-3">
    <h5 class="card-header">Quick Links</h5>
    <div class="card-body">
        <div class="list-group">
            <a class="list-group-item list-group-item-action" href="{% url 'projects:index' %}"><strong>Projects</strong></a>
            <a class="list-group-item disabled list-group-item-action" href="#">People</a>
            <a class="list-group-item disabled list-group-item-action" href="#">Meetings</a>
            <a class="list-group-item list-group-item-action" href="{% url 'council:index' %}"><strong>Council Insights</strong></a>
            <a class="list-group-item disabled list-group-item-action" href="#">Work Planner</a>
            <a class="list-group-item disabled list-group-item-action" href="#">Continuing Education</a>
        </div>
    </div>
</div>
    
{% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Login</a>
{% endif %}
{% endblock %}